language: python
python:
  - "3.5"
  - "3.6"

env:
  global:
    - HYDRA_LAUNCHER=fork
    - OMPI_MCA_rmaps_base_oversubscribe=yes
    - MPI=mpich

before_install:
    - sudo apt-get update -q
    - python$PY -m pip install Cython
    - python$PY -m pip install numpy
    - bash parsl/executors/extreme_scale/install-mpi.sh $MPI
    - python$PY --version
    - python$PY -m cython --version
    - python$PY -c "import numpy;print(numpy.__version__)"
    - if [[ "$MPI" == "mpich"   ]]; then mpichversion; fi
    - if [[ "$MPI" == "openmpi" ]]; then ompi_info;    fi

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install .[extreme_scale]

# Os tests
os:
    - linux

# command to run tests
script:
    - export PARSL_TESTING="true"
    - pip install -r test-requirements.txt
    - bash parsl/tests/run.sh
